kubectl apply -f .\k8s\00-namespace.yaml
kubectl apply -f .\k8s\configmap.yaml
kubectl apply -f .\k8s\secret.yaml
kubectl apply -f .\k8s\mysql-pvc.yaml
kubectl apply -f .\k8s\mysql-deployment.yaml
kubectl apply -f .\k8s\mysql-service.yaml
kubectl apply -f .\k8s\backend-deployment.yaml
kubectl apply -f .\k8s\backend-service.yaml
kubectl apply -f .\k8s\frontend-deployment.yaml
kubectl apply -f .\k8s\frontend-service.yaml
kubectl apply -f .\k8s\network-policy.yaml
kubectl apply -f .\k8s\gateway.yaml
