apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: quiz-bank
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP    # 프론트엔드에서만 내부 접근
