apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-config
  namespace: quiz-bank
data:
  DB_HOST:      "mysql-service"
  DB_PORT:      "3306"
  BACKEND_URL:  "http://backend-service:5000"
  FRONTEND_PROXY_TIMEOUT: "75"
  FLASK_DEBUG:  "false"
  GEMINI_MODEL: "gemini-2.0-flash"
  GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models"
  GEMINI_TIMEOUT: "20"
  PURGE_DEFAULT_ON_BOOT: "true"
  USE_SQLITE_FALLBACK: "true"
