apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hc-quiz-bank
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  FLASK_DEBUG: "false"
  GEMINI_MODEL: "gemini-2.5-flash"
  GEMINI_MODEL_CANDIDATES: "gemini-2.5-flash,gemini-2.0-flash-lite"
  GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models"
  GEMINI_TIMEOUT: "60"
  PURGE_DEFAULT_ON_BOOT: "true"
  USE_SQLITE_FALLBACK: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: hc-quiz-bank
data:
  BACKEND_URL: "http://backend-service:5000"
  FLASK_DEBUG: "false"
  FRONTEND_PROXY_TIMEOUT: "120"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: hc-quiz-bank
data:
  TZ: "Asia/Seoul"