apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz-bank
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080      # 외부 접속: http://<NODE_IP>:30080
      protocol: TCP
  type: NodePort
