apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: quiz-bank
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP    # 클러스터 내부에서만 접근 (외부 노출 X)
