apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: hc-quiz-bank
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP    # ?대윭?ㅽ꽣 ?대??먯꽌留??묎렐 (?몃? ?몄텧 X)


