apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  DB_USER: quizuser
  DB_PASSWORD: quizpassword
  DB_NAME: quizdb
  GEMINI_API_KEY:   AIzaSyAgfg3UXgbQQeWAe507OZN6N8lI1vXBrRw
  ADMIN_SECRET_KEY: a880ca0e30de1f1013af31175ae564c1533fd7398034e6c5a8da5222b90407ca
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  DB_USER: quizuser
  DB_PASSWORD: quizpassword
  DB_NAME: quizdb
  MYSQL_ROOT_PASSWORD: rootpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  FRONTEND_DUMMY_SECRET: "change-me"