apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hc-quiz-bank
type: Opaque
data:
  DB_USER: cXVpenVzZXI=
  DB_PASSWORD: cXVpenBhc3N3b3Jk
  DB_NAME: cXVpemRi
  GEMINI_API_KEY: UkVQTEFDRV9ZT1VSX0dFTUlOSV9BUElfS0VZ
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: hc-quiz-bank
type: Opaque
data:
  DB_USER: cXVpenVzZXI=
  DB_PASSWORD: cXVpenBhc3N3b3Jk
  DB_NAME: cXVpemRi
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  FRONTEND_DUMMY_SECRET: "change-me"


