apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  DB_USER: "REPLACE_DB_USER"
  DB_PASSWORD: "REPLACE_DB_PASSWORD"
  DB_NAME: "REPLACE_DB_NAME"
  GEMINI_API_KEY: "REPLACE_GEMINI_API_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  DB_USER: "REPLACE_DB_USER"
  DB_PASSWORD: "REPLACE_DB_PASSWORD"
  DB_NAME: "REPLACE_DB_NAME"
  MYSQL_ROOT_PASSWORD: "REPLACE_MYSQL_ROOT_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: hc-quiz-bank
type: Opaque
stringData:
  FRONTEND_DUMMY_SECRET: "REPLACE_FRONTEND_SECRET"


